[phases.setup]
# Only define packages here
nixPkgs = ["php83", "nginx", "libmysqlclient"]
# Removed the nixLibs line

[phases.install]
dependsOn = ["setup"]
cmds = [
  "mkdir -p /var/log/nginx",
  "mkdir -p /var/cache/nginx"
]

# Ensure [phases.start] is completely removed

[start]
cmd = "node /assets/scripts/prestart.mjs /assets/nginx.template.conf /nginx.conf && (php-fpm -y /assets/php-fpm.conf & nginx -c /nginx.conf)"
