[phases.setup]
nixPkgs = ["php83", "nginx", "libmysqlclient"]

[phases.install]
dependsOn = ["setup"]
cmds = [
  "mkdir -p /var/log/nginx",
  "mkdir -p /var/cache/nginx"
]

# Removed the [phases.start] section

[start]
cmd = "node /assets/scripts/prestart.mjs /assets/nginx.template.conf /nginx.conf && (php-fpm -y /assets/php-fpm.conf & nginx -c /nginx.conf)"
